#!/bin/bash

UUT1=acq2106_076
UUT2=acq2106_079
# INBOX: acq2106_076, 6 x AI424
# OUTBOX: acq2106_079, 2 x AO424


set_clocks_internal() {
	echo TCVRT02 setup, setting internal clock, internal trigger
    	(cd ~/PROJECTS/ACQ400/HAPI/acq400_hapi
#	 SITECLIENT_TRACE=1
	./user_apps/acq2106/acq2106_set_sync_role.py \
	--master_clk zclk,1000000,100 --master_trg=soft --clkdiv=$EXTCLKDIV \
	$UUT1 $UUT2
	)
}

set_clocks_external() {
	echo TCVRT02 setup, setting external clock, external trigger
        (cd ~/PROJECTS/ACQ400/HAPI/acq400_hapi
#        SITECLIENT_TRACE=1
        ./user_apps/acq2106/acq2106_set_sync_role.py \
        --master_clk fp,1000000,1000000 --master_trg=fp,falling --clkdiv=$EXTCLKDIV          \
        $UUT1 $UUT2
        )
}

setup_2106_system()
{
       echo TCVRT02 setup, setting up ADC and DAC connections
       (cd ~/PROJECTS/AFHBA404/HAPI;
       SITECLIENT_TRACE=1
       DOSITES="5,6" PWMSITES="6" python ./llc-test-harness-twobox.py $UUT1 $UUT2
       )
       
       # moved to /mnt/local/rc.user on acq2106_076 fs
       #echo TCVRT02 activating ADC us timer
       #ssh root@acq2106_076 '/usr/local/bin/set.site 0 spad1_us 1,2,1'
       
}

setup_pwm_output() {
    echo TCVRT02 setup, setting up PWM outputs
    cd ~/PROJECTS/AFHBA404/LLCONTROL/
    # Inserts PWM control data into the host buffer.
    # Set all channels to 0.
    #PWM_OFFSET=132 DEVNUM=1 IBUF=0 ./pwm_set_channel 0 0
    # Set first channel for test.
    export CH_NUM=0 # 0 is all channels.
    export INITIAL_STATE=1
    export GROUP_PERIOD=1000
    export ICOUNT=250
    export OCOUNT=750
    PWM_OFFSET=132 DEVNUM=1 IBUF=0 ./pwm_set_channel $CH_NUM $INITIAL_STATE $GROUP_PERIOD $ICOUNT $OCOUNT
    cd ~
}


case "x$1" in
xinternal)
	# 10kHz, internal clock
	export EXTCLKDIV=${EXTCLKDIV:-100}

	set_clocks_internal
	setup_2106_system
	setup_pwm_output
	
	;;
xexternal)
	# 10kHz, external clock, Si5326 bypassed
	# export EXTCLKDIV=${EXTCLKDIV:-1}

	# 10kHz, external 1MHz clock, Si5326 not bypassed (normal operation)
	export EXTCLKDIV=${EXTCLKDIV:-100}

	set_clocks_external
	setup_2106_system
	setup_pwm_output
	
	;;
x)
	$0 external
	;;
esac





